//
// Given two strings s and t which consist of only lowercase letters.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Find the letter that was added in t.
//
// Example:
//
// Input:
// s = "abcd"
// t = "abcde"
//
// Output:
// e
//
// Explanation:
// 'e' is the letter that was added.
//


class Solution {
public:
    char findTheDifference(string s, string t) {
        int sn[26] = {0}, tn[26] = {0};
        for(auto ch: s){
            ++ sn[ch - 'a'];
        }
        for(auto ch: t){
            ++ tn[ch - 'a'];
        }
        for(int i = 0; i < 26; ++ i){
            if(sn[i] == tn[i])
                continue;
            if(tn[i] > sn[i])
                return i + 'a';
        }
        return 'a';
    }
};
